# Generated by Django 3.1.7 on 2021-08-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=10)),
                ('employee_phone', models.CharField(max_length=10)),
                ('employee_department', models.CharField(max_length=10)),
                ('employee_gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'not specified')], max_length=10)),
            ],
        ),
    ]
